In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.replace({True:1 ,False:0})
dataset

C:\Users\PRIYANKA MANI\AppData\Local\Temp\ipykernel_37728\1644727536.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1 ,False:0})

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
 from sklearn.model_selection import GridSearchCV
 from sklearn.tree import DecisionTreeRegressor
 param_grid = {'criterion':['squared_error','friedman_mse','poisson','absolute_error'],
                'max_features': ['auto','sqrt','log2'],
                'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
 
grid.fit(independent, dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
29 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
11 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.67577747 0.62273679 0.62414588 0.60094532
        nan        nan 0.64923735 0.63091754 0.65560822 0.61314731
        nan        nan 0.68564189 0.59299631 0.66367894 0.64154762
        nan        nan 0.64429786 0.64294714 0.62050391 0.67518579]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'poisson', 'absolute_error'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [8]:
re=grid.cv_results_
print("TheR_score valueforbestparameter{}:".format(grid.best_params_))

TheR_score valueforbestparameter{'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'}:

In [9]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002266,0.000981,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002424,0.000808,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.008774,0.004029,0.005834,0.002964,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.682953,0.634581,0.718491,0.605523,0.737339,0.675777,0.049595,2
3,0.008964,0.001245,0.005937,0.002231,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.645448,0.500127,0.582372,0.654581,0.731156,0.622737,0.077391,12
4,0.008218,0.000995,0.004082,0.000696,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.444495,0.610011,0.743847,0.688677,0.633700,0.624146,0.101052,11
5,0.005803,0.001018,0.004272,0.000456,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.673163,0.560122,0.536890,0.647131,0.587420,0.600945,0.051577,15
6,0.001846,0.000352,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.002094,0.004188,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.006772,0.000925,0.004260,0.001858,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.672361,0.618372,0.698875,0.569344,0.687233,0.649237,0.048534,6
9,0.006223,0.001588,0.004720,0.000973,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.587088,0.500954,0.715993,0.705460,0.645093,0.630918,0.079758,10
10,0.007890,0.001286,0.003633,0.000809,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.727996,0.519346,0.722823,0.605533,0.702344,0.655608,0.081261,5
11,0.007887,0.002609,0.002647,0.001609,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.644165,0.515420,0.675194,0.649927,0.581031,0.613147,0.057873,14
12,0.001382,0.001777,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.000956,0.001394,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.006930,0.004229,0.004674,0.003820,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.704657,0.618108,0.719128,0.655206,0.731110,0.685642,0.042515,1
15,0.008833,0.000750,0.004777,0.001854,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.637129,0.415742,0.680069,0.614841,0.617200,0.592996,0.091664,16
16,0.013390,0.002815,0.002221,0.001385,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.714579,0.544849,0.643013,0.695506,0.720448,0.663679,0.065382,4
17,0.010572,0.002910,0.004086,0.001527,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.689417,0.549330,0.609413,0.699660,0.659918,0.641548,0.055754,9
18,0.000000,0.000000,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001082,0.001396,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.023276,0.002290,0.002825,0.001509,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.759188,0.600061,0.559353,0.720660,0.582227,0.644298,0.080070,7
21,0.019733,0.001012,0.002673,0.000846,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.718051,0.500975,0.748643,0.574685,0.672382,0.642947,0.092189,8
22,0.026976,0.001863,0.003211,0.000982,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.574721,0.626237,0.420587,0.749161,0.731813,0.620504,0.119196,13
23,0.017684,0.001323,0.002614,0.000738,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.695051,0.622845,0.679038,0.692252,0.686743,0.675186,0.026735,3

In [10]:
import pickle
filename="finalized_model_Decisiontree.sav"
pickle.dump(grid, open(filename,'wb'))

In [11]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 35
BMI: 32
Children: 3
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [12]:
loaded_model=pickle.load(open("finalized_model_Decisiontree.sav",'rb'))
result=loaded_model.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([39597.4072])