In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.replace({True:1 ,False:0})
dataset

C:\Users\PRIYANKA MANI\AppData\Local\Temp\ipykernel_48592\1644727536.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1 ,False:0})

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','absolute_error','friedman_mse','poisson'],
             'max_features': ['auto','sqrt','log2'],
             'n_estimators':[50,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
 # fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
32 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.83243953 0.83424347 0.83049565 0.83370678
        nan        nan 0.83208838 0.83092063 0.8315568  0.83190662
        nan        nan 0.83007881 0.83576281 0.83063219 0.83513013
        nan        nan 0.83149639 0.83133204 0.83310277 0.83429698]
  warnings.warn(
C:\Anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [50, 100]},
             verbose=3)

In [9]:
re=grid.cv_results_
print("TheR_score valueforbestparameter{}:".format(grid.best_params_))

TheR_score valueforbestparameter{'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}:

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002225,0.000208,0.000000,0.000000,squared_error,auto,50,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.001865,0.000434,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.183644,0.023832,0.008739,0.001628,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.861286,0.781914,0.859036,0.826863,0.833098,0.832440,0.028719,7
3,0.435701,0.061178,0.056072,0.002222,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.860541,0.777554,0.860297,0.832647,0.840179,0.834243,0.030403,4
4,0.179551,0.023009,0.020602,0.012652,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.855417,0.781443,0.857579,0.822250,0.835790,0.830496,0.027773,15
5,0.976570,0.068482,0.056617,0.003776,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.859294,0.776320,0.856084,0.830877,0.845958,0.833707,0.030354,5
6,0.004754,0.002534,0.000000,0.000000,absolute_error,auto,50,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.003151,0.001670,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,1.939727,0.015641,0.038965,0.003281,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.859133,0.781732,0.849051,0.825118,0.845407,0.832088,0.027499,8
9,3.840081,0.045962,0.060343,0.003615,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.852275,0.779232,0.849576,0.827848,0.845672,0.830921,0.027213,13
10,1.947194,0.020823,0.035683,0.003527,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.852154,0.776321,0.860923,0.824602,0.843785,0.831557,0.030118,10
11,3.911204,0.022545,0.058775,0.000994,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857232,0.781799,0.855500,0.821665,0.843336,0.831907,0.028087,9
12,0.004390,0.003727,0.000000,0.000000,friedman_mse,auto,50,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.005802,0.005070,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.572582,0.003738,0.032907,0.002878,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.859923,0.774448,0.860432,0.825331,0.830260,0.830079,0.031399,16
15,1.131156,0.003373,0.062744,0.003302,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.857218,0.786323,0.863196,0.832328,0.839749,0.835763,0.027147,1
16,0.575849,0.010530,0.036205,0.003006,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.851485,0.777557,0.857139,0.829475,0.837505,0.830632,0.028295,14
17,1.142394,0.006418,0.060457,0.003190,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858472,0.782632,0.862902,0.829119,0.842525,0.835130,0.028855,2
18,0.006731,0.003205,0.000000,0.000000,poisson,auto,50,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001077,0.002154,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.883182,0.004310,0.038542,0.005117,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.856612,0.772456,0.857475,0.833641,0.837297,0.831496,0.031080,11
21,1.651809,0.006868,0.046567,0.008880,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.857551,0.776963,0.857129,0.827413,0.837603,0.831332,0.029542,12
22,0.868773,0.006784,0.035876,0.003332,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.858533,0.783281,0.850643,0.828479,0.844578,0.833103,0.026794,6
23,1.308162,0.047190,0.033651,0.005008,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.858626,0.781955,0.863465,0.829275,0.838164,0.834297,0.029061,3

In [11]:
import pickle
filename="finalized_model_RF.sav"
pickle.dump(grid, open(filename,'wb'))

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 12
BMI: 15
Children: 0
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 0

In [13]:
loaded_model=pickle.load(open("finalized_model_RF.sav",'rb'))
result=loaded_model.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1935.4514543])