In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.replace({True:1 ,False:0})
dataset

C:\Users\PRIYANKA MANI\AppData\Local\Temp\ipykernel_14188\1644727536.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1 ,False:0})

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','sigmoid','linear'],
            'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid=GridSearchCV(SVR(), param_grid, refit=True, verbose=2, n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid', 'linear']},
             verbose=2)

In [9]:
re=grid.cv_results_
print("TheR_score valueforbestparameter{}:".format(grid.best_params_))

TheR_score valueforbestparameter{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}:

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.130411,0.013874,0.037073,0.003097,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.113791,-0.110741,-0.079156,-0.103389,-0.106488,-0.102713,0.012303,16
1,0.078071,0.015879,0.012755,0.002250,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
2,0.098719,0.009330,0.013857,0.002451,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,10
3,0.103381,0.009739,0.033844,0.004454,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,15
4,0.121418,0.027676,0.021152,0.004094,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,22
5,0.078808,0.012582,0.011843,0.001751,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,10
6,0.170049,0.036741,0.080539,0.027357,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.100012,-0.098456,-0.072981,-0.096615,-0.102232,-0.094059,0.010699,14
7,0.079775,0.026100,0.019002,0.005965,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
8,0.251336,0.107443,0.030509,0.018784,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,7
9,0.185868,0.112292,0.098700,0.050563,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,27
10,0.343614,0.016747,0.074501,0.004077,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,25
11,0.584580,0.026852,0.040633,0.004427,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,7
12,0.632799,0.006175,0.129634,0.007702,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.080692,-0.054347,-0.062876,-0.079329,-0.117983,-0.079045,0.021865,13
13,0.235227,0.008160,0.047296,0.004061,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
14,1.957018,0.207597,0.039690,0.006432,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
15,0.355515,0.016986,0.124579,0.004516,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,26
16,0.361149,0.006260,0.078679,0.002341,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,28
17,2.019592,0.208670,0.044737,0.006299,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
18,0.892479,0.048145,0.136093,0.004241,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.033126,-0.002835,-0.026545,-0.029140,-0.067392,-0.031808,0.020699,12
19,0.246019,0.007763,0.050908,0.005034,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
20,3.308955,0.211589,0.040569,0.004882,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,3
21,0.364781,0.008623,0.141735,0.006344,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.143510,-0.087595,-0.113312,-0.128591,-0.193992,-0.133400,0.035492,24
22,0.387348,0.002027,0.082685,0.001029,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-7.209317,-9.282940,-7.776578,-7.745074,-6.891719,-7.781126,0.821557,29
23,3.310196,0.216460,0.042815,0.002878,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,3
24,1.082080,0.060220,0.139892,0.005977,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.011741,0.043659,0.013383,0.021694,-0.012948,0.015506,0.018217,9
25,0.264877,0.008760,0.051909,0.003015,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
26,4.999654,0.789704,0.028820,0.004775,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,5
27,0.366725,0.007445,0.132384,0.002214,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,23
28,0.381651,0.006583,0.079136,0.004655,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-15.561853,-20.498908,-17.095474,-16.750877,-15.012168,-16.983856,1.914783,30
29,4.544461,0.749213,0.025615,0.002527,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,5

In [17]:
import pickle
filename="finalized_model_SVM.sav"
pickle.dump(grid, open(filename,'wb'))

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 21
BMI: 32
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 0

In [19]:
loaded_model=pickle.load(open("finalized_model_SVM.sav",'rb'))
result=loaded_model.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

array([2462.41262556])